name: ESLint Self

on: [workflow_dispatch]

jobs:
    eslint:
        name: Run eslint scanning
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install ESLint
              run: |
                  yarn add eslint@8.10.0 -D
                  yarn add @microsoft/eslint-formatter-sarif@2.1.7 -D

            - name: Run ESLint
              run: |
                  yarn eslint ./**/*.js
              continue-on-error: true
